version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.7.0
    container_name: logstash
    hostname: logstash
    ports:
      - 9600:9600
      - 8089:8089
    volumes:
      - .\logstash:/usr/share/logstash/pipeline/
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.11.1
    container_name: filebeat
    hostname: filebeat
    volumes: 
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./application.log:/home/spring-boot-h2-crud/application.log
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch

  api:
    build:
      context: .
    privileged: true
    volumes:
      - ~/.m2:/root/.m2
      - ./:/home/spring-boot-h2-crud
      #- ./config/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
    command: mvn spring-boot:run -DskipTests
    ports:
      - "8088:8088"   
    links:
      - filebeat:filebeat
    depends_on:
      - filebeat