# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#================================ General =====================================
name: "${HOSTNAME:MY_HOST}"
#=========================== Filebeat prospectors =============================

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
# OPTIONS: https://www.elastic.co/guide/en/beats/filebeat/master/configuration-filebeat-options.html
filebeat.inputs:
  - type: log
    enabled: true
    #multiline.pattern: '^(\d){4}\W(\d){2}\W(\d){2}\s{1}(\d){2}\W(\d){2}\W(\d){2}\S{1}\s{1}'
    #multiline.pattern:  '^%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{TIME}.*'
    multiline.pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}"
    # multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
    multiline.negate: true
    multiline.match: after
    paths:
      - /home/spring-boot-h2-crud/application.log
      - /application.log
      - /spring-boot-h2-crud/application.log
      

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:8089"]
  bulk_max_size: 1024
  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]
  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"
  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
